### ISSUE TITLE
tauri-build 1.3与tauri 1.3有问题？

### ISSUE THREAD

**Issue by rixingyike** [tauri-apps/create-tauri-app#425] opened 2023-05-20 03:14 UTC
我按照官方的简易教程，运行不起来，打开Cargo.toml文件，发现里有这样的版本依赖：

`[build-dependencies]
tauri-build = { version = "1.3.0", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "1.3.0", features = [] }`

开始总是提示：`error: no matching package named `winnow` found`

后来我见别人的示例，tauri-build 与tauri的版本都是1.2，可以能过，于是换成1.2，重新编译，通过了。

![image](https://github.com/tauri-apps/create-tauri-app/assets/3161864/42f284a3-16ff-40b6-8336-65ee916e9c9c)

难道是1.3版本有问题吗？

系统：macOS
rustc：1.69.0

**Comment by amrbashir** [comment] 2023-05-22 21:44
1.3 works fine for me, could you change it back to `1.3` and run `cargo update` in `src-tauri` and try again?

**Comment by rixingyike** [comment] 2023-05-22 23:34
Still not working，here's how my script executes when I changed version to 1.3:

```
$ rustc --version
rustc 1.69.0 (84c898d65 2023-04-16)
$ cd work/blog_writer/src-tauri 
$ cargo update
    Updating crates.io index
error: no matching package named `winnow` found
location searched: registry `crates-io`
required by package `tauri-build v1.3.0`
    ... which satisfies dependency `tauri-build = "^1.3.0"` of package `app v0.1.0 (/Users/liyi/work/blog_writer/src-tauri)`
```

The system version is macOS 12.2

@amrbashir

**Comment by amrbashir** [comment] 2023-05-23 01:12
try removing `target` and `Cargo.lock` and try again, I still can't reproduce

**Comment by rixingyike** [comment] 2023-05-23 14:13
> 

Do as you say，the result is the same as before：

```
$ cargo update
    Blocking waiting for file lock on package cache
    Updating crates.io index
error: no matching package named `winnow` found
location searched: registry `crates-io`
required by package `tauri-build v1.3.0`
    ... which satisfies dependency `tauri-build = "^1.3.0"` of package `app v0.1.0 (/Users/liyi/work/blog_writer/src-tauri)`
```

I don't know what the problem is, but I don't really care, because 1.2 version will work just as well for me.

**Comment by jose8109** [comment] 2023-10-18 14:36
Por favor me ayudan a controlarlo, necesito una solución urgente. Gracias yo soy Ovalle Jose Luis correo joseluisovalle2024@gmail.com pepeislove21@gmail.com y todos los demás correos vinculados en la cuentas en Twitter soy @pepeislove21 fueron completamente hackeadas y modificadas en los tiempos de línea cambiando las configuraciones @Github.com ayuda

**Comment by amrbashir** [comment] 2023-12-12 23:22
Closing since I can't reproduce, if this still happens to you, pleas let me know

**Closed as not planned by amrbashir** 2023-12-12 23:22 UTC
