### ISSUE TITLE
create-tauri-app multiple templates are broken

### ISSUE THREAD

**Issue by Jagholin** [tauri-apps/create-tauri-app#261] opened 2022-12-11 15:34 UTC
Link to discord discussion: https://discord.com/channels/616186924390023171/1051492348707741787

problem description: not much to say, other than I try to create a tauri app using this tool. So far, Ive tried `react`, `react-js`, `vue` templates with the same problem(compiled program shows blank window). 

commands that i run:
``` 
cargo create-tauri-app
 (choose package manager: npm)
npm install
npm run tauri dev
```

No errors are produced. Opening dev tools -> JS console always shows an error , different in each project type(see discord thread link for examples)

All prerequisits from https://tauri.app/v1/guides/getting-started/prerequisites are installed. I didnt install pnpm or yarn, since they are alternatives to npm

`cargo create-tauri-app --version` outputs 2.7.2

Example of the problem, using Vue
![grafik](https://user-images.githubusercontent.com/4126782/206912725-01a51e1a-609f-4993-8e09-01fd294acd22.png)

Tauri info output:
![grafik](https://user-images.githubusercontent.com/4126782/206912811-9ccf3332-57cd-4b86-9dfc-89885c949d46.png)

**Comment by amrbashir** [comment] 2022-12-11 17:38
Can't seem to reproduce the issue. The problem is in building the front-end, try removing `node_modules` and clearing the global npm cache. Also try running `npm run dev` and open it in the browser and see if anything is wrong.

**Comment by Jagholin** [comment] 2022-12-11 18:28
did both (`npm cache clean --force` and removing `node_modules` with `package-lock.json`), no effect.

`npm run dev` also shows empty page in the browser with the same error in the devtools console.

**Comment by amrbashir** [comment] 2022-12-11 19:04
well, this is a problem with the bundler (vite) and I am not yet able to reproduce it and seems very specific to your machine. can you try `npm create vite@latest`, choose a template and run it in the browser?

**Comment by Jagholin** [comment] 2022-12-11 19:13
Ok, I've tried 2 project types:
react with JavaScript
vue with TypeScript

both run well(see screenshot from vue template)
![grafik](https://user-images.githubusercontent.com/4126782/206923896-230c077a-46d1-49e7-8130-ea7a56b5b1e9.png)

**Comment by Jagholin** [comment] 2022-12-11 19:25
Huh now tauri seems to work too... I guess the only thing thats different is `npm create vite@latest` somehow seems to fix stuff...

I guess i close this issue

**Comment by Jagholin** [comment] 2022-12-12 19:12
I'm reopening this issue due to some new information.

So a bit of background - I have a HDD and a SSD on my pc. SSD is the smaller one (~500gb) so I only use it for Windows and some frequently-used big programs. Most of the Users folder like documents downloads etc. are on the HDD, except for one thing - some folders are placed physically on SSD but are linked using NTFS junctions with a folder in HDD. One of these special folders is where I usually place rust projects - due to how much drive access is used during compilation I like the boost that placing this folder on SSD gives me. So the whole thing looks something like this:

```
C:  <- this is SSD
 | --   accelerate_linked
 |         | -- rust 
 |         | -- .cargo, .rustup are also here

D: <- this is HDD
 | --  Users/UserName directory
 |        | -- rust    -> links to C:\accelerate_linked\rust
 |        | -- webdev  -  just a normal folder
 |        | -- documents  and other stuff
```

so let us see what happens shall we? this is the experiment: 
```
1. cd to D:\Users\rust directory. 
2. run cargo create-tauri-app
3. select something like package manager: npm, project type: react-ts
4. cd into the project directory
5. npm install && npm run tauri dev
```
result: blank window.
```
6. take the project folder and copy it somewhere else (d:\Users\webdev)
7. cd into the copied folder
8. npm run tauri dev (!!)
```
result: everything works
```
9. cd into C:\accelerate_linked\rust\project folder
10. npm run tauri dev
```
result: everything is fine

So this appears to be a bug, right?... the question is only where

**Comment by Jagholin** [comment] 2022-12-12 19:30
huh appears to be vite bug https://github.com/vitejs/vite/issues/10802

**Comment by amrbashir** [comment] 2022-12-12 20:03
thanks for taking the time to track this down. gonna close this issue and hopefully the vite team will fix it soon.

**Closed as not planned by amrbashir** 2022-12-12 20:03 UTC
Labels: bug, status: upstream
